Vise Clave-logo fra svg. Drar inn bibliotek: gatsby-plugin-react-svg
ClaveConsulting/hjemmeside pull request #5
Opened 2019-10-08 20:31 UTC by evilppo

Ingen animasjoner enda.

2019-10-08 20:33 UTC, evilppo commented
Fargen på logo satt til svart for å være mer synlig frem til vi får på plass animering

2019-10-09 05:56 UTC, peteabre requested changes
Er noe med linkene som er blitt endret etter at logoen ble introdusert. Se screenshot
<img width="544" alt="Skjermbilde 2019-10-09 kl  07 54 23" src="https://user-images.githubusercontent.com/4180788/66455160-42d1f600-ea6a-11e9-932c-5fb78cacee69.png">

2019-10-09 15:12 UTC, evilppo commented
> Er noe med linkene som er blitt endret etter at logoen ble introdusert. Se screenshot
> <img alt="Skjermbilde 2019-10-09 kl 07 54 23" width="544" src="https://user-images.githubusercontent.com/4180788/66455160-42d1f600-ea6a-11e9-932c-5fb78cacee69.png">

Peter: Fikset i: 9dfa868

2019-10-10 07:04 UTC, peteabre approved these changes

2019-10-14 06:18 UTC, merged